name: Docker Image CI - latest

on:
  push:
    branches:
      - master

jobs:
  docker:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-docker]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build & Push to Docker Hub
        uses: opspresso/action-docker@v0.2.1
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          REGISTRY: docker.pkg.github.com
          IMAGE_NAME: 'satont/twitch-vk-announcer'
          TAG_NAME: master:latest
